
- name: Traefik routes
  become: true
  copy:
    src: ../files/routes.yml
    dest: /data/containers/traefik/config.yml
    owner: ansible
    group: docker

- name: Restart traefik
  become: true
  shell:
    cmd: "docker compose -f /data/services/traefik.yml restart traefik"
  ignore_errors: true
