- name: Add host into the 05-jellyfin.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-jellyfin.conf"
    line: "cname=jellyfin.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for Jellfin stack
  template:
    src: docker-compose.j2
    dest: /data/services/jellyfin.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/jellyfin.yml up -d"
