---
- hosts: 'proxmox_control_node_by_ip'
  remote_user: root
  tasks:
    - name: apt update
      include_tasks: roles/common/tasks/apt-update.yml

#- hosts: "workstations"
#  tasks:
#    - name: apt update
#      include_tasks: roles/common/tasks/apt-update.yml

- hosts: 'pihole'
  remote_user: ansible
  tasks:
    - name: "Update PiHole"
      include_tasks: roles/pihole/tasks/update.yml

- hosts: 'pihole-exporter'
  remote_user: ansible
  tasks:
    - name: "Update PiHole Exporter"
      include_tasks: roles/pihole-exporter/tasks/update.yml

- hosts: "prometheus"
  remote_user: ansible
  tasks:
    - name: "Update Prometheus"
      include_tasks: roles/prometheus/tasks/update.yml

- hosts: "nebula-sync"
  remote_user: ansible
  tasks:
    - name: "Update Nebula Sync"
      include_tasks: roles/nebula-sync/tasks/update.yml

- hosts: "n8n"
  remote_user: ansible
  tasks:
    - name: "Update N8N"
      include_tasks: roles/n8n/tasks/update.yml

- hosts: "containers"
  remote_user: ansible
  tasks:
    - name: "Update Traefik"
      include_tasks: roles/traefik/tasks/update.yml
    - name: "Update Portainer"
      include_tasks: roles/portainer/tasks/update.yml

- hosts: "diun"
  remote_user: ansible
  tasks:
    - name: "Update Diun"
      include_tasks: roles/diun/tasks/update.yml

- hosts: "edge"
  remote_user: ansible
  tasks:
    - name: "Update Traefik"
      include_tasks: roles/traefik/tasks/update.yml
    - name: "Update Cloudflare DDNS"
      include_tasks: roles/cloudflare-ddns/tasks/update.yml
    - name: "Update WireGuard Easy"
      include_tasks: roles/wg-easy/tasks/update.yml

- hosts: "portainer"
  remote_user: ansible
  tasks:
    - name: "Update Portainer"
      include_tasks: roles/portainer/tasks/update.yml

- hosts: "jellyfin"
  remote_user: ansible
  tasks:
    - name: "Update Jellyfin"
      include_tasks: roles/jellyfin/tasks/update.yml

- hosts: "freshrss"
  remote_user: ansible
  tasks:
    - name: "Update FreshRSS"
      include_tasks: roles/freshrss/tasks/update.yml

- hosts: "audiobookshelf"
  remote_user: ansible
  tasks:
    - name: "Update Audiobookshelf"
      include_tasks: roles/audiobookshelf/tasks/update.yml

- hosts: "tubearchivist"
  remote_user: ansible
  tasks:
    - name: "Update TubeArchivist"
      include_tasks: roles/tubearchivist/tasks/update.yml

- hosts: "blinko"
  remote_user: ansible
  tasks:
    - name: "Update Blinko"
      include_tasks: roles/blinko/tasks/update.yml

- hosts: "baserow"
  remote_user: ansible
  tasks:
    - name: "Update Baserow"
      include_tasks: roles/baserow/tasks/update.yml

- hosts: "outline"
  remote_user: ansible
  tasks:
    - name: "Update Outline"
      include_tasks: roles/outline/tasks/update.yml

- hosts: "kimai"
  remote_user: ansible
  tasks:
    - name: "Update Kimai"
      include_tasks: roles/kimai/tasks/update.yml
      when: groups['kimai'] is defined and groups['kimai'] | length > 0

#- hosts: 'managed_hosts'
#  remote_user: ansible
#  tasks:
#    - name: "Update BorgBackup"
 #     include_tasks: roles/borgbackup/tasks/update.yml

#- hosts: 'containers:watchtower:dns:edge'
#  remote_user: ansible
#  tasks:
#    - name: "Update containers"
#      include_tasks: roles/watchtower/tasks/update.yml

