---
- hosts: 'proxmox_control_node_by_ip:managed_hosts'
  remote_user: root
  tasks:
    - name: apt update
      include_tasks: roles/common/tasks/apt-update.yml

- hosts: "workstations"
  tasks:
    - name: apt update
      include_tasks: roles/common/tasks/apt-update.yml

- hosts: 'containers:watchtower:dns:external-proxy'
  remote_user: ansible
  tasks:
    - name: "Update containers"
      include_tasks: roles/watchtower/tasks/update.yml
