---
- name: "Setup PiHole DNS"
  hosts: pihole
  remote_user: ansible
  become: true
  tasks:
    - name: "Run PiHole setup if group exists"
      include_tasks: roles/pihole/tasks/setup.yml
      run_once: true
      when: groups['pihole'] is defined and groups['pihole'] | length > 0

- name: "Setup Nebula Sync"
  hosts: nebula-sync
  remote_user: ansible
  become: true
  tasks:
    - name: "Run Nebula Sync setup if group exists"
      include_tasks: roles/nebula-sync/tasks/setup.yml
      run_once: true
      when: groups['nebula-sync'] is defined and groups['nebula-sync'] | length > 0

- name: "Setup Kimai"
  hosts: kimai
  connection: local
  tasks:
    - name: "Run Kimai setup if group exists"
      include_tasks: roles/kimai/tasks/setup.yml
      run_once: true
      when: groups['kimai'] is defined and groups['kimai'] | length > 0

- name: "Setup Immich"
  hosts: immich
  connection: local
  tasks:
    - name: "Run Immich setup if group exists"
      include_tasks: roles/immich/tasks/setup.yml
      run_once: true
      when: groups['immich'] is defined and groups['immich'] | length > 0

- name: "Setup Plex"
  hosts: localhost
  connection: local
  tasks:
    - name: "Run Plex setup if group exists"
      include_tasks: roles/plex/tasks/setup.yml
      run_once: true
      when: groups['plex'] is defined and groups['plex'] | length > 0

- name: "Setup kasm"
  hosts: kasm
  connection: local
  tasks:
    - name: "Run kasm setup if group exists"
      include_tasks: roles/kasm/tasks/setup.yml
      run_once: true
      when: groups['kasm'] is defined and groups['kasm'] | length > 0

- name: "Setup Prometheus"
  hosts: prometheus
  connection: local
  tasks:
    - name: "Run Prometheus setup if group exists"
      include_tasks: roles/prometheus/tasks/setup.yml
      run_once: true
      when: groups['prometheus'] is defined and groups['prometheus'] | length > 0
