---
- name: "Setup PiHole DNS"
  hosts: pihole
  remote_user: ansible
  become: true
  tasks:
    - name: "Run PiHole setup if group exists"
      include_tasks: roles/pihole/tasks/setup.yml
      run_once: true
      when: groups['pihole'] is defined and groups['pihole'] | length > 0

- name: "Setup PiHole Exporter"
  hosts: pihole-exporter
  connection: local
  tasks:
    - name: "Run PiHole Exporter setup if group exists"
      include_tasks: roles/pihole-exporter/tasks/setup.yml
      run_once: true
      when: groups['pihole-exporter'] is defined and groups['pihole-exporter'] | length > 0

- name: "Setup Nebula Sync"
  hosts: nebula-sync
  remote_user: ansible
  become: true
  tasks:
    - name: "Run Nebula Sync setup if group exists"
      include_tasks: roles/nebula-sync/tasks/setup.yml
      run_once: true
      when: groups['nebula-sync'] is defined and groups['nebula-sync'] | length > 0

- name: "Setup Kimai"
  hosts: kimai
  connection: local
  tasks:
    - name: "Run Kimai setup if group exists"
      include_tasks: roles/kimai/tasks/setup.yml
      run_once: true
      when: groups['kimai'] is defined and groups['kimai'] | length > 0

- name: "Setup Immich"
  hosts: immich
  connection: local
  tasks:
    - name: "Run Immich setup if group exists"
      include_tasks: roles/immich/tasks/setup.yml
      run_once: true
      when: groups['immich'] is defined and groups['immich'] | length > 0

- name: "Setup Plex"
  hosts: localhost
  connection: local
  tasks:
    - name: "Run Plex setup if group exists"
      include_tasks: roles/plex/tasks/setup.yml
      run_once: true
      when: groups['plex'] is defined and groups['plex'] | length > 0

- name: "Setup kasm"
  hosts: kasm
  connection: local
  tasks:
    - name: "Run kasm setup if group exists"
      include_tasks: roles/kasm/tasks/setup.yml
      run_once: true
      when: groups['kasm'] is defined and groups['kasm'] | length > 0

- name: "Setup Prometheus"
  hosts: prometheus
  connection: local
  tasks:
    - name: "Run Prometheus setup if group exists"
      include_tasks: roles/prometheus/tasks/setup.yml
      run_once: true
      when: groups['prometheus'] is defined and groups['prometheus'] | length > 0

- name: "Setup Semaphore"
  hosts: semaphore
  connection: local
  tasks:
    - name: "Run Semaphore setup if group exists"
      include_tasks: roles/semaphore/tasks/setup.yml
      run_once: true
      when: groups['semaphore'] is defined and groups['semaphore'] | length > 0

- name: "Setup Jellyfin"
  hosts: jellyfin
  connection: local
  tasks:
    - name: "Run Jellyfin setup if group exists"
      include_tasks: roles/jellyfin/tasks/setup.yml
      run_once: true
      when: groups['jellyfin'] is defined and groups['jellyfin'] | length > 0

- name: "Setup Audiobookshelf"
  hosts: audiobookshelf
  connection: local
  tasks:
    - name: "Run Audiobookshelf setup if group exists"
      include_tasks: roles/audiobookshelf/tasks/setup.yml
      run_once: true
      when: groups['audiobookshelf'] is defined and groups['audiobookshelf'] | length > 0

- name: "Setup TubeArchivist"
  hosts: tubearchivist
  connection: local
  tasks:
    - name: "Run TubeArchivist setup if group exists"
      include_tasks: roles/tubearchivist/tasks/setup.yml
      run_once: true
      when: groups['tubearchivist'] is defined and groups['tubearchivist'] | length > 0

- name: "Setup Obsidian"
  hosts: obsidian
  connection: local
  tasks:
    - name: "Run Obsidian setup if group exists"
      include_tasks: roles/obsidian/tasks/setup.yml
      run_once: true
      when: groups['obsidian'] is defined and groups['obsidian'] | length > 0

- name: "Setup Blinko"
  hosts: blinko
  connection: local
  tasks:
    - name: "Run Blinko setup if group exists"
      include_tasks: roles/blinko/tasks/setup.yml
      run_once: true
      when: groups['blinko'] is defined and groups['blinko'] | length > 0

- name: "Setup Cloudflare DDNS"
  hosts: edge
  connection: local
  tasks:
    - name: "Run Cloudflare DDNS setup if group exists"
      include_tasks: roles/cloudflare-ddns/tasks/setup.yml
      run_once: true
      when: groups['edge'] is defined and groups['edge'] | length > 0

- name: "Setup WireGuard Easy"
  hosts: edge
  connection: local
  tasks:
    - name: "Run WireGuard Easy setup if group exists"
      include_tasks: roles/wg-easy/tasks/setup.yml
      run_once: true
      when: groups['edge'] is defined and groups['edge'] | length > 0
