---
# playbook for setting up proxmox
- hosts: "proxmox_control_node_by_ip"
  remote_user: root
  roles:
    - role: proxmox

- hosts: "managed_hosts"
  remote_user: root
  tasks:
    - name: 'Apt update'
      include_tasks: roles/common/tasks/apt-update.yml
    - name: 'Add users'
      include_tasks: roles/common/tasks/users.yml

- hosts: "workstations"
  tasks:
    - name: 'Apt update'
      include_tasks: roles/common/tasks/apt-update.yml
    - name: 'Add users'
      include_tasks: roles/common/tasks/users.yml

- hosts: "raspberrypi"
  remote_user: pi
  tasks:
    - name: Add users
      include_tasks: roles/common/tasks/users.yml

- hosts: "arrs"
  remote_user: ansible
  roles:
    - role: shares
    - role: arrs

- hosts: "whisparr"
  remote_user: ansible
  roles:
    - role: shares
    - role: whisparr

- hosts: "overseer"
  remote_user: ansible
  roles:
    - role: overseer

- hosts: "freshrss"
  remote_user: ansible
  roles:
    - role: freshrss

- hosts: "homeassistant"
  remote_user: ansible
  roles:
    - role: homeassistant

- hosts: "linkding"
  remote_user: ansible
  roles:
    - role: linkding

# Deprecate
#- hosts: "plex_stack"
#  remote_user: ansible
#  roles:
#    - role: shares
#    - role: plex
#    - role: tautulli
#     - role: plex-meta-manager
#

- hosts: tautulli
  remote_user: ansible
  roles:
    - role: tautulli

- hosts: kometa
  remote_user: ansible
  roles:
    - role: kometa

- hosts: "navidrome"
  remote_user: ansible
  roles:
    - role: navidrome

- hosts: "jellyfin"
  remote_user: ansible
  roles:
    - role: shares
    - role: jellyfin

- hosts: "plex"
  remote_user: ansible
  roles:
    - role: shares
    - role: plex

- hosts: "tdarr"
  remote_user: ansible
  roles:
    - role: shares
    - role: tdarr

- hosts: "tautulli"
  remote_user: ansible
  roles:
    - role: tautulli

- hosts: "tubearchivist"
  remote_user: ansible
  roles:
    - role: tubearchivist

- hosts: "obsidian"
  remote_user: ansible
  roles:
    - role: obsidian

- hosts: "traggo"
  remote_user: ansible
  roles:
    - role: traggo

- hosts: "semaphore"
  remote_user: ansible
  roles:
    - role: semaphore

- hosts: "ghostfolio"
  remote_user: ansible
  roles:
    - role: ghostfolio

- hosts: "kavita"
  remote_user: ansible
  roles:
    - role: shares
    - role: kavita

- hosts: "audiobookshelf"
  remote_user: ansible
  roles:
    - role: shares
    - role: audiobookshelf

# Plan to deprecate this
- hosts: "docker"
  remote_user: ansible
  roles:
    - role: portainer
    - role: watchtower
 ####

- hosts: "containers"
  remote_user: ansible
  roles:
    - role: portainer
    - role: watchtower
    - role: traefik

- hosts: "portainer"
  remote_user: ansible
  roles:
    - role: portainer

- hosts: "watchtower"
  remote_user: ansible
  roles:
    - role: watchtower

- hosts: "duplicati"
  remote_user: ansible
  roles:
    - role: duplicati

- hosts: "dns"
  remote_user: ansible
  roles:
    - role: pihole

# Plan to depricate this group for 'edge'
- hosts: "external-proxy"
  remote_user: ansible
  roles:
    - role: traefik
    - role: authelia
    - role: cloudflare-ddns
    - role: wg-easy
  tasks:
    - name: "Update external routes"
      include_tasks: roles/traefik/tasks/update_routes_external.yml
#####

- hosts: "edge"
  remote_user: ansible
  roles:
    - role: traefik
    - role: authelia
    - role: cloudflare-ddns
    - role: wg-easy
  tasks:
    - name: "Update external routes"
      include_tasks: roles/traefik/tasks/update_routes_external.yml

- hosts: "photoprism"
  remote_user: ansible
  roles:
    - role: shares
    - role: photoprism

- hosts: "paperless-ng"
  remote_user: ansible
  roles:
    - role: shares
    - role: paperless-ng

- hosts: "homepage"
  remote_user: ansible
  roles:
    - role: homepage

- hosts: "nextcloud"
  remote_user: ansible
  roles:
    - role: nextcloud

- hosts: "baserow"
  remote_user: ansible
  roles:
    - role: baserow

- hosts: "n8n"
  remote_user: ansible
  roles:
    - role: n8n

- hosts: "monica"
  remote_user: ansible
  roles:
    - role: monica

- hosts: "ofelia"
  remote_user: ansible
  roles:
    - role: ofelia

- hosts: "syncthing"
  remote_user: ansible
  roles:
    - role: syncthing
