---
- hosts: pihole
  remote_user: ansible
  become: true
  tasks:
    - include_tasks: roles/pihole/tasks/setup.yml
      run_once: true

- hosts: nebula-sync
  remote_user: ansible
  become: true
  tasks:
    - include_tasks: roles/nebula-sync/tasks/setup.yml
      run_once: true

- hosts: localhost
  connection: local
  tasks:
    - include_tasks: roles/kimai/tasks/setup.yml
      run_once: true

- hosts: localhost
  connection: local
  tasks:
    - include_tasks: roles/immich/tasks/setup.yml
      run_once: true
