---
- hosts: "managed_hosts"
  remote_user: root
  tasks:
    - name: 'Apt update'
      include_tasks: roles/common/tasks/apt-update.yml
    - name: 'Add users'
      include_tasks: roles/common/tasks/users.yml

- hosts: "raspberrypi"
  remote_user: pi
  tasks:
    - name: Add users
      include_tasks: roles/common/tasks/users.yml

- hosts: "arrs"
  remote_user: ansible
  roles:
    - role: shares
    - role: arrs

- hosts: "whisparr"
  remote_user: ansible
  roles:
    - role: shares
    - role: whisparr

- hosts: "jellyseerr"
  remote_user: ansible
  roles:
    - role: jellyseerr

- hosts: "overseer"
  remote_user: ansible
  roles:
    - role: overseer

- hosts: "freshrss"
  remote_user: ansible
  roles:
    - role: freshrss

- hosts: "homeassistant"
  remote_user: ansible
  roles:
    - role: homeassistant

- hosts: "teslamate"
  remote_user: ansible
  roles:
    - role: teslamate

- hosts: "linkding"
  remote_user: ansible
  roles:
    - role: linkding

- hosts: tautulli
  remote_user: ansible
  roles:
    - role: tautulli

- hosts: kometa
  remote_user: ansible
  roles:
    - role: kometa

- hosts: "navidrome"
  remote_user: ansible
  roles:
    - role: navidrome

- hosts: "jellyfin"
  remote_user: ansible
  roles:
    - role: shares
    - role: jellyfin

- hosts: "plex"
  remote_user: ansible
  roles:
    - role: shares
    - role: plex

- hosts: "tdarr"
  remote_user: ansible
  roles:
    - role: shares
    - role: tdarr

- hosts: "tautulli"
  remote_user: ansible
  roles:
    - role: tautulli

- hosts: "tubearchivist"
  remote_user: ansible
  roles:
    - role: tubearchivist

- hosts: "obsidian"
  remote_user: ansible
  roles:
    - role: obsidian

- hosts: "cura"
  remote_user: ansible
  roles:
    - role: cura

- hosts: "traggo"
  remote_user: ansible
  roles:
    - role: traggo

- hosts: "semaphore"
  remote_user: ansible
  roles:
    - role: semaphore

- hosts: "ghostfolio"
  remote_user: ansible
  roles:
    - role: ghostfolio

- hosts: "kavita"
  remote_user: ansible
  roles:
    - role: shares
    - role: kavita

- hosts: "audiobookshelf"
  remote_user: ansible
  roles:
    - role: shares
    - role: audiobookshelf

# Plan to deprecate this
- hosts: "docker"
  remote_user: ansible
  roles:
    - role: portainer
    - role: watchtower
 ####

- hosts: "containers"
  remote_user: ansible
  roles:
    - role: portainer
    - role: watchtower
    - role: traefik

- hosts: "portainer"
  remote_user: ansible
  roles:
    - role: portainer

- hosts: "watchtower"
  remote_user: ansible
  roles:
    - role: watchtower

- hosts: "duplicati"
  remote_user: ansible
  roles:
    - role: duplicati

- hosts: "pihole"
  remote_user: ansible
  roles:
    - role: pihole

# Core Infrastructure
- name: "Deploy PiHole DNS"
  hosts: pihole
  remote_user: ansible
  roles:
    - role: pihole
      tags:
        - pihole

- name: "Depoy Nebula Sync"
  hosts: "nebula-sync"
  remote_user: ansible
  roles:
    - role: nebula-sync
      tags:
        - nebula-sync

- hosts: "edge"
  remote_user: ansible
  roles:
    - role: traefik
    - role: authelia
    - role: cloudflare-ddns
    - role: wg-easy
  tasks:
    - name: "Update external routes"
      include_tasks: roles/traefik/tasks/update_routes_external.yml

# - hosts: "prometheus"
#   remote_user: ansible
#   roles:
#     - role: prometheus

# - hosts: "pihole-exporter"
#   remote_user: ansible
#   roles:
#     - role: pihole-exporter

- hosts: "photoprism"
  remote_user: ansible
  roles:
    - role: shares
    - role: photoprism

- hosts: "paperless-ng"
  remote_user: ansible
  roles:
    - role: shares
    - role: paperless-ng

- hosts: "homepage"
  remote_user: ansible
  roles:
    - role: homepage

- hosts: "nextcloud"
  remote_user: ansible
  roles:
    - role: nextcloud

- hosts: "baserow"
  remote_user: ansible
  roles:
    - role: baserow

- hosts: "n8n"
  remote_user: ansible
  roles:
    - role: n8n

- hosts: "docmost"
  remote_user: ansible
  roles:
    - role: docmost

- hosts: "monica"
  remote_user: ansible
  roles:
    - role: monica

- hosts: "ofelia"
  remote_user: ansible
  roles:
    - role: ofelia

- hosts: "syncthing"
  remote_user: ansible
  roles:
    - role: syncthing

- hosts: "kimai"
  remote_user: ansible
  roles:
    - role: kimai

- hosts: "immich"
  remote_user: ansible
  roles:
    - role: immich
