---
- name: Update DNS custom.list
  remote_user: ansible
  hosts: "dns"
  tasks:
    - name: Update PiHole
      include_tasks: roles/pihole/tasks/update_dns.yml

- name: Update Externally facing proxy routes
  remote_user: ansible
  hosts: "external-proxy"
  tasks:
    - name: Update Traefik
      include_tasks: roles/traefik/tasks/update_routes_external.yml
