---
# Watchtower Removal Playbook
# This playbook removes Watchtower from all hosts
#
# Usage:
#   ansible-playbook watchtower-removal.yml
#
# To also remove Watchtower config data:
#   ansible-playbook watchtower-removal.yml -e "remove_config_data=true"

- name: "Remove Watchtower from docker hosts"
  hosts: "docker:containers:watchtower"
  remote_user: ansible
  become: true
  vars:
    remove_config_data: false  # Set to true to remove config data directories

  tasks:
    - name: Display removal warning
      debug:
        msg: |
          ============================================
          Removing Watchtower from {{ ansible_facts['hostname'] }}
          Config data removal: {{ remove_config_data }}
          ============================================

    - name: Stop Watchtower container
      community.docker.docker_compose_v2:
        project_src: /data/services
        files:
          - watchtower.yml
        state: absent
      ignore_errors: true
      register: container_stop

    - name: Alternative - Stop via docker compose command
      shell:
        cmd: "docker compose -f /data/services/watchtower.yml down"
      when: container_stop is failed
      ignore_errors: true

    - name: Alternative - Force remove container
      shell:
        cmd: "docker rm -f watchtower"
      when: container_stop is failed
      ignore_errors: true

    - name: Remove docker-compose file
      ansible.builtin.file:
        path: /data/services/watchtower.yml
        state: absent

    - name: Remove Watchtower config directory
      ansible.builtin.file:
        path: "/data/containers/watchtower_{{ ansible_facts['hostname'] }}"
        state: absent
      when: remove_config_data | bool

    - name: Display completion message
      debug:
        msg: |
          ============================================
          Watchtower removed from {{ ansible_facts['hostname'] }}

          Removed:
            - Docker container
            - Compose file: /data/services/watchtower.yml
            {% if remove_config_data %}
            - Config: /data/containers/watchtower_{{ ansible_facts['hostname'] }}
            {% endif %}

          Next steps:
            1. Remove Watchtower inventory definitions and role from codebase (manual)
            2. Remove container labels from service docker-compose templates (manual)
          ============================================
