- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker
  tags:
    - debian
    - ubuntu

- name: Copy watchtower docker compose
  become: true
  template:
    src: docker-compose.j2
    dest: /data/services/watchtower.yml
  tags:
    - ubuntu
    - debian

- name: Run container
  become: true
  shell:
    cmd: "docker compose -f /data/services/watchtower.yml up -d"
  tags:
    - ubuntu
    - debian
