##  /etc/rsyslog.conf	Configuration file for rsyslog.
#
#			For more information see
#			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
#
#  Default logging rules can be found in /etc/rsyslog.d/50-default.conf


#################
#### MODULES ####
#################

$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support
#$ModLoad immark  # provides --MARK-- message capability

# Enable non-kernel facility klog messages
$KLogPermitNonKernelFacility on
#$ModLoad imtcp.so

{% if salt['grains.get']('id') == salt['pillar.get']('rsyslog:server:name') -%}
{% endif -%}
# start a UDP listener for the remote router
$ModLoad imudp    # load UDP server plugin
#$AllowedSender UDP, *.nucleoid.com # permit only the router
$UDPServerRun 514 # listen on default syslog UDP port 514

# make gtls driver the default
#$DefaultNetstreamDriver gtls

# Provides TCP syslog reception
#$InputTCPServerStreamDriverMode 1 # run driver in TLS-only mode
#$InputTCPServerStreamDriverAuthMode x509/name
{% if salt['grains.get']('id') == salt['pillar.get']('rsyslog:server:name') -%}
#$InputTCPServerRun {{ salt['pillar.get']('rsyslog:server:port') }}
{% endif -%}
#$InputTCPServerStreamDriverPermittedPeer *.nucleoid.com

#$WorkDirectory /var/spool/rsyslog # where to place spool files
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down

# certificate files
#$DefaultNetstreamDriverCAFile /etc/ssl/rsyslog/ca.pem
#$DefaultNetstreamDriverCertFile /etc/ssl/rsyslog/machine-cert.pem
#$DefaultNetstreamDriverKeyFile /etc/ssl/rsyslog/machine-key.pem

# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@{{ salt['pillar.get']('rsyslog:server:name') }}:{{ salt['pillar.get']('rsyslog:server:port') }}
#*.* @@{{ salt['pillar.get']('rsyslog:server:name') }}:514
# ### end of the forwarding rule ###


###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

