---
- name: Install mounting dependencies
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - cifs-utils
    - nfs-common
    - nfs4-acl-tools
    - avahi-daemon
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

