plugin: community.general.proxmox
user: root@pam
validate_certs: false
want_proxmox_nodes_ansible_host: false
want_facts: true
keyed_groups:
    # proxmox_tags_parsed is an example of a fact only returned when 'want_facts=true'
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group
groups:
  arrs: "'arrs' in (proxmox_tags_parsed|list)"
  overseer: "'overseer' in (proxmox_tags_parsed|list)"
  freshrss: "'freshrss' in (proxmox_tags_parsed|list)"
  linkding: "'linkding' in (proxmox_tags_parsed|list)"
  plex_stack: "'plex_stack' in (proxmox_tags_parsed|list)"
  plex: "'plex' in (proxmox_tags_parsed|list)"
  tautulli: "'tautulli' in (proxmox_tags_parsed|list)"
  # plex-meta-manager
  pmm: "'pmm' in (proxmox_tags_parsed|list)"
  backups: "'backups' in (proxmox_tags_parsed|list)"
  duplicati: "'duplicati' in (proxmox_tags_parsed|list)"
  documents: "'documents' in (proxmox_tags_parsed|list)"
  dns: "'dns' in (proxmox_tags_parsed|list)"
  docker: "'docker' in (proxmox_tags_parsed|list)"
  containers: "'containers' in (proxmox_tags_parsed|list)"
  portainer: "'portainer' in (proxmox_tags_parsed|list)"
  watchtower: "'watchtower' in (proxmox_tags_parsed|list)"
  traefik_internal: "'traefik_internal' in (proxmox_tags_parsed|list)"
  proxy_external: "'proxy_external' in (proxmox_tags_parsed|list)"
  photos: "'photos' in (proxmox_tags_parsed|list)"
  homepage: "'homepage' in (proxmox_tags_parsed|list)"
  nextcloud: "'nextcloud' in (proxmox_tags_parsed|list)"
  ritchieplex: "'ritchieplex' in (proxmox_tags_parsed|list)"
compose:
  ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ansible.utils.ipaddr('address')
