- name: Create traefik cname folder
  file:
    path: "{{ playbook_dir }}/files/dns"
    state: directory
  delegate_to: 127.0.0.1

- name: Add host into the 05-traefik.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/05-traefik.conf"
    # regexp: ".* {{ ansible_hostname }}.local.{{ homelab_domain }}"
    # line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.int.{{ homelab_domain }}"
    line: "cname=traefik.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1
