  - name: Create DNS containers
    community.general.proxmox:
      vmid: "{{ item.vmid }}"
      hostname: '{{ item.name }}'
      node: '{{ item.proxmox_node  }}'
      api_user: '{{ proxmox_api.api_user }}'
      api_host: '{{ proxmox_api.api_host }}'
      api_token_id: '{{ proxmox_api.api_token_id }}'
      api_token_secret: '{{ proxmox_api.api_token_secret }}'
      memory: 2048
      swap: 4096
      disk: 'local-lvm:64'
      password: '{{ item.root_password }}'
      pubkey: '{{ item.pubkey }}'
      timezone: '{{ timezone }}'
      cores: 1
      ostemplate: local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst
      netif: '{"net0":"name=eth0,gw={{ item.gateway }},ip={{ item.ip_addr }},bridge=vmbr0"}'
      nameserver: '{{ item.nameserver }}'
      unprivileged: false
      tags:
        - dns
        - containers
    loop: '{{ lxcs_dns }}'
    when: lxcs_dns is defined

  - name: Ensure nesting enabled for DNS lxcs
    ansible.builtin.lineinfile:
      path: /etc/pve/lxc/{{ item.vmid }}.conf
      line: "features: nesting=1"
      regexp: '^features: .*'
      state: present
    loop: '{{ lxcs_dns }}'
    when: lxcs_dns is defined

  - name: Ensure DNS lxcs start on boot enabled
    ansible.builtin.lineinfile:
      path: /etc/pve/lxc/{{ item.vmid }}.conf
      line: "onboot: 1"
      regexp: '^onboot: .*'
      state: present
    loop: '{{ lxcs_dns }}'
    when: lxcs_dns is defined

  - name: Start DNS containers
    community.general.proxmox:
      vmid: "{{ item.vmid }}"
      hostname: '{{ item.name }}'
      node: '{{ item.proxmox_node  }}'
      api_user: '{{ proxmox_api.api_user }}'
      api_host: '{{ proxmox_api.api_host }}'
      api_token_id: '{{ proxmox_api.api_token_id }}'
      api_token_secret: '{{ proxmox_api.api_token_secret }}'
      state: started
    loop: '{{ lxcs_dns }}'
    when: lxcs_dns is defined
