# https://technotim.live/posts/first-11-things-proxmox/
#
- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - python3-proxmoxer

- name: Add required Debian repositories to sources.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: "{{ item.line }}"
    create: yes
    state: present
  loop:
    - line: "deb http://deb.debian.org/debian bookworm main contrib"
    - line: "deb http://deb.debian.org/debian bookworm-updates main contrib"
    - line: "deb http://security.debian.org/debian-security bookworm-security main contrib"

- name: Comment out specific Proxmox Enterprise repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
    line: '#deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
    create: yes
    backrefs: yes

- name: Ensure repository line is present in pve-install-repo.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-install-repo.list
    line: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    create: yes
    state: present

- name: Correcting Ceph package repositories 
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^{{ item.line }}'
    line: '#{{ item.line }}'
    create: yes
    backrefs: yes
  loop:
    - line: "deb http://download.proxmox.com/debian/ceph-quincy bookworm enterprise"
    - line: "deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription"
    - line: "deb http://download.proxmox.com/debian/ceph-reef bookworm enterprise"
    - line: "deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription"

- name: Update LXC images
  ansible.builtin.shell:
    cmd: pveam update

- name: Download the Debian 12 standard template
  ansible.builtin.shell:
    cmd: pveam download local debian-12-standard_12.2-1_amd64.tar.zst

# pveam update


