# ============================================
# Ansible Inventory Generation
# ============================================
# Generates an INI-format inventory file for Ansible
# based on containers provisioned by Terraform.

resource "local_file" "ansible_inventory" {
  filename = "${path.module}/../ansible/inventory/generated/terraform-hosts.ini"
  content  = <<-EOT
# ===========================================
# Terraform-Generated Ansible Inventory
# ===========================================
# This file is auto-generated by Terraform.
# Do not edit manually - changes will be overwritten.
# ===========================================

[pihole]
%{for name, container in module.dns_containers~}
${name}.int.${var.homelab_domain} ansible_host=${split("/", container.ip_address)[0]}
%{endfor~}

[edge]
%{for name, container in module.edge_containers~}
${name}.int.${var.homelab_domain} ansible_host=${split("/", container.ip_address)[0]}
%{endfor~}

[containers]
%{for name, container in module.monitoring_containers~}
${name}.int.${var.homelab_domain} ansible_host=${split("/", container.ip_address)[0]}
%{endfor~}

[prometheus]
%{for name, container in module.monitoring_containers~}
${name}.int.${var.homelab_domain}
%{endfor~}

[services]
%{for name, container in module.services_containers~}
${name}.int.${var.homelab_domain} ansible_host=${split("/", container.ip_address)[0]}
%{endfor~}
%{for group, containers in local.services_by_group~}

[${group}]
%{for name in containers~}
${name}.int.${var.homelab_domain}
%{endfor~}
%{endfor~}
EOT
}

output "ansible_inventory_path" {
  description = "Path to the generated Ansible inventory file"
  value       = local_file.ansible_inventory.filename
}
