- name: Install terminal mail client setup
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop:
    - neomutt
    - isync
    - msmtp
    - lynx
    - xdg-utils
  when: ansible_distribution == 'Arch Linux'

- name: Install terminal mail client setup
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - neomutt
    - isync
    - msmtp
    - lynx
    - xdg-utils
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Remove evolution
  become: yes
  apt:
    name: "{{item}}"
    state: absent
    update_cache: yes
  loop:
    - evolution
  when: ansible_distribution == 'Ubuntu'

- name: install Thunderbird
  become: yes
  flatpak:
    name: org.mozilla.Thunderbird
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
