- name: "Mount NextCloud share"
  include_tasks: roles/shares/tasks/single_share.yml
  vars:
    type: "{{ named_shares['nextcloud']['type'] }}"
    destination: "{{ named_shares['nextcloud']['destination'] }}"
    source: "{{ named_shares['nextcloud']['source'] }}"
    options: "{{ named_shares['nextcloud']['options'] }}"

- name: Create services folder
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Create data folder
  ansible.builtin.file:
    path: /data/containers/
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for NextCloud
  template:
    src: docker-compose.j2
    dest: /data/services/nextcloud.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/nextcloud.yml up -d"
