- name: Create services folder (cura)
  become: true
  ansible.builtin.file:
    path: /data/services/cura
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file (cura) 
  template:
    src: docker-compose.j2
    dest: /data/services/cura/compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/cura/compose.yml up -d"
