- name: Add host into the 05-semaphore.conf for Semaphore
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-semaphore.conf"
    line: "{{ item }}"
    create: true
  loop:
    - "cname=semaphore.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    - "cname=semaphore.local.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
  delegate_to: 127.0.0.1

- name: Create services folder
  ansible.builtin.file:
    path: /data/services/semaphore
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for Semaphore stack
  template:
    src: docker-compose.j2
    dest: /data/services/semaphore/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/semaphore/docker-compose.yml up -d"
