- name: Add host into the 05-ghostfolio.conf for Ghostfolio
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-ghostfolio.conf"
    line: "{{ item }}"
    create: true
  loop:
    - "cname=ghostfolio.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
  delegate_to: 127.0.0.1

- name: Create services folder
  ansible.builtin.file:
    path: /data/services/ghostfolio
    state: directory
    owner: ansible
    group: docker

- name: Setup environment file for Ghostfolio stack
  template:
    src: env.j2
    dest: /data/services/ghostfolio/.env
    owner: ansible
    group: docker

- name: Setup docker compose file for Ghostfolio stack
  template:
    src: docker-compose.j2
    dest: /data/services/ghostfolio/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/ghostfolio/docker-compose.yml up -d"
