- name: Create services folder
  ansible.builtin.file:
    path: /data/services/paperless-ng
    state: directory
    owner: ansible
    group: docker

- name: Add host into the 05-paperless-ng.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-paperless-ng.conf"
    line: "{{ item }}"
    create: true
  loop:
    - "cname=paperless-ng.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
  delegate_to: 127.0.0.1

- name: Setup docker compose file for paperless-ng
  template:
    src: docker-compose.j2
    dest: /data/services/paperless-ng/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/paperless-ng/docker-compose.yml up -d"
