- name: Create services folder
  ansible.builtin.file:
    path: /data/services/paperless-ng
    state: directory
    owner: ansible
    group: docker

- name: Create data folder
  ansible.builtin.file:
    path: /data/containers/
    state: directory
    owner: ansible
    group: docker

- name: Create proxy network
  become: yes
  shell:
    cmd: "docker network create proxy"
  ignore_errors: true

- name: Create paperless-ng cname folder
  file:
    path: "{{ playbook_dir }}/files/dns/"
    state: directory
  delegate_to: 127.0.0.1

- name: Add host into the 05-paperless-ng.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/05-paperless-ng.conf"
    # regexp: ".* {{ ansible_hostname }}.local.{{ homelab_domain }}"
    # line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.int.{{ homelab_domain }}"
    line: "cname=paperless-ng.local.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Setup docker compose file for paperless-ng
  template:
    src: docker-compose.j2
    dest: /data/services/paperless-ng/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/paperless-ng/docker-compose.yml up -d"
