- name: Authelia config
  become: true
  template:
    src: ../templates/configuration.j2
    dest: /data/containers/authelia/configuration.yml
    owner: ansible
    group: docker

- name: Authelia users database
  become: true
  copy:
    src: ../files/users_database.yml
    dest: /data/containers/authelia/users_database.yml
    owner: ansible
    group: docker

- name: Restart authelia
  shell:
    cmd: "docker compose -f /data/services/authelia.yml restart authelia"
  ignore_errors: true
