- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for plex-meta-manager stack
  template:
    src: docker-compose.j2
    dest: /data/services/plex-meta-manager.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/plex-meta-manager.yml up -d"
