- name: Create a backup folder for the host
  become: yes
  ansible.builtin.file:
    path: "/mnt/ContainerBackups/{{ ansible_hostname }}"
    state: directory

- name: Create Duplicati data folder
  become: yes
  ansible.builtin.file:
    path: "/data/containers/duplicati_{{ ansible_hostname }}"
    state: directory
    owner: ansible
    group: docker

- name: Add host into the 05-duplicati.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-duplicati.conf"
    # regexp: ".* {{ ansible_hostname }}.local.{{ homelab_domain }}"
    # line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.int.{{ homelab_domain }}"
    line: "cname=duplicati.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Setup docker compose file for Duplicati
  become: yes
  template:
    src: docker-compose.j2
    dest: /data/services/duplicati.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/duplicati.yml up -d"
