- name: Add host into the 05-kavita.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-kavita.conf"
    line: "cname=kavita.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Create kavita folder
  become: true
  ansible.builtin.file:
    path: /data/services/kavita
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for Kavita stack
  template:
    src: docker-compose.j2
    dest: /data/services/kavita/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/kavita/docker-compose.yml up -d"
