- name: Add host into the 05-traefik.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-traefik.conf"
    line: "cname=traefik.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1
