
- name: Traefik routes
  copy:
    src: "{{ playbook_dir }}/files/traefik/config.yml"
    dest: "/data/containers/traefik/config.yml"

- name: Restart traefik
  become: true
  shell:
    cmd: "docker compose -f /data/services/traefik.yml restart traefik"
