- name: Create services folder (teslamate)
  become: true
  ansible.builtin.file:
    path: /data/services/teslamate
    state: directory
    owner: ansible
    group: docker

- name: Create teslamate data directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0755'
  loop:
    - { path: /data/containers/teslamate/import, owner: ansible, group: docker }
    - { path: /data/containers/teslamate/grafana, owner: "472", group: "472" }

- name: Setup docker compose file (teslamate)
  template:
    src: docker-compose.j2
    dest: /data/services/teslamate/compose.yml
    owner: ansible
    group: docker

- name: Copy environment configuration
  copy:
    src: "{{ playbook_dir }}/../homelab_config/ansible/files/config/teslamate/environment"
    dest: /data/services/teslamate/.env
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/teslamate/compose.yml up -d"
