- name: Add host into the 05-overseer.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-overseer.conf"
    line: "cname=overseer.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for the overseer stack
  template:
    src: docker-compose.j2
    dest: /data/services/overseer.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/overseer.yml up -d"
