
- name: Create dns folder
  file:
    path: "{{ playbook_dir }}/files/dns"
    state: directory
  delegate_to: 127.0.0.1

- name: Add host into the 05-arrs.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/05-arrs.conf"
    line: "cname={{ item.name }}.local.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  loop:
    - { name: 'overseer' }
  delegate_to: 127.0.0.1

- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for arrs stack
  template:
    src: docker-compose.j2
    dest: /data/services/overseer.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/overseer.yml up -d"
