- name: Add host into the 05-syncthing.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-syncthing.conf"
    line: "cname=syncthing.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Create syncthing folder
  become: true
  ansible.builtin.file:
    path: /data/services/syncthing
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for Syncthing stack
  template:
    src: docker-compose.j2
    dest: /data/services/syncthing/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/syncthing/docker-compose.yml up -d"
