- name: Create services folder (nebula-sync)
  become: true
  ansible.builtin.file:
    path: /data/services/nebula-sync
    state: directory
    owner: ansible
    group: docker

- name: Copy environment configuration
  copy:
    src: "{{ playbook_dir }}/files/config/nebula-sync/environment"
    dest: /data/services/nebula-sync/.env
    owner: ansible
    group: docker

- name: Setup docker compose file (nebula-sync)
  template:
    src: docker-compose.j2
    dest: /data/services/nebula-sync/compose.yml
    owner: ansible
    group: docker

- name: Run container
  become: true
  shell:
    cmd: "docker compose -f /data/services/nebula-sync/compose.yml up -d"
