- name: Add host into the 05-arrs.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-arrs.conf"
    # regexp: ".* {{ ansible_hostname }}.local.{{ homelab_domain }}"
    # line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.int.{{ homelab_domain }}"
    line: "cname={{ item.name }}.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  loop:
    - { name: 'prowlarr' }
    - { name: 'flaresolverr' }
    - { name: 'radarr' }
    - { name: 'sonarr' }
    - { name: 'bazarr' }
    - { name: 'readarr' }
    - { name: 'mylar' }
    - { name: 'sabnzbd' }
    - { name: 'transmission' }
  delegate_to: 127.0.0.1

- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for arrs stack
  template:
    src: docker-compose.j2
    dest: /data/services/arrs.yml
    owner: ansible
    group: docker

# This is where Sabnzbd and Transmission will dump files
- name: Create arrs download folder
  become: true
  ansible.builtin.file:
    path: /data/arrs/
    state: directory
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/arrs.yml up -d"
