- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for arrs stack
  template:
    src: docker-compose.j2
    dest: /data/services/arrs.yml
    owner: ansible
    group: docker

# This is where Sabnzbd and Transmission will dump files
- name: Create arrs download folder
  become: true
  ansible.builtin.file:
    path: /data/arrs/
    state: directory
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/arrs.yml up -d"
