
- name: Create dns folder
  file:
    path: "{{ playbook_dir }}/files/dns"
    state: directory
  delegate_to: 127.0.0.1

- name: Add host into the 05-traggo.conf for Traggo
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/05-traggo.conf"
    line: "cname=traggo.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Add host into the 05-traggo.conf for Traggo
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/05-traggo.conf"
    line: "cname=traggo.local.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Create services folder
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for Traggo stack
  template:
    src: docker-compose.j2
    dest: /data/services/traggo.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/traggo.yml up -d"
