- name: Add host into the 05-monica.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/cname/05-monica.conf"
    line: "{{ item }}"
    create: true
  loop:
    - "cname=monica.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
  delegate_to: 127.0.0.1

- name: Create services folder
  become: true
  ansible.builtin.file:
    path: /data/services/monica
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for Monica PRM stack
  template:
    src: docker-compose.j2
    dest: /data/services/monica/docker-compose.yml
    owner: ansible
    group: docker

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/monica/docker-compose.yml up -d"
