
- name: Create dns folder
  file:
    path: "{{ playbook_dir }}/files/dns"
    state: directory
  delegate_to: 127.0.0.1

- name: Add host into the 05-tubearchivist.conf for TubeArchivist
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/05-tubearchivist.conf"
    line: "cname=tubearchivist.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Create services folder
  ansible.builtin.file:
    path: /data/services/
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for TubeArchivist stack
  template:
    src: docker-compose.j2
    dest: /data/services/tubearchivist.yml
    owner: ansible
    group: docker

# Fix to elastic search issue: https://github.com/tubearchivist/tubearchivist?tab=readme-ov-file#common-errors
- name: Ensure elastic search folder has the correct owner
  become: true
  ansible.builtin.file:
    path: /data/containers/tubearchivist/es
    state: directory
    recurse: true
    owner: 1000

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/tubearchivist.yml up -d"
