- name: Create tubearchivist services folder
  ansible.builtin.file:
    path: /data/services/tubearchivist
    state: directory
    owner: ansible
    group: docker

- name: Setup docker compose file for TubeArchivist stack
  template:
    src: docker-compose.j2
    dest: /data/services/tubearchivist/compose.yml
    owner: ansible
    group: docker

# Fix to elastic search issue: https://github.com/tubearchivist/tubearchivist?tab=readme-ov-file#common-errors
- name: Ensure elastic search folder has the correct owner
  become: true
  ansible.builtin.file:
    path: /data/containers/tubearchivist/es
    state: directory
    recurse: true
    owner: 1000

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/tubearchivist/compose.yml up -d"
