- name: Setup docker compose file for PiHole
  template:
    src: docker-compose.j2
    dest: /data/services/pihole.yml
    owner: ansible
    group: docker

- name: Update resolv.d file (1.1.1.1)
  become: true
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 1.1.1.1'

- name: Update resolv.d file (1.0.0.1)
  become: true
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 1.0.0.1'

- name: Create PiHole cname folder
  file:
    path: "{{ playbook_dir }}/files/dns"
    state: directory
  delegate_to: 127.0.0.1

- name: Add host into the 05-pihole.conf for pihole
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/05-pihole.conf"
    # regexp: ".* {{ ansible_hostname }}.local.{{ homelab_domain }}"
    # line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.int.{{ homelab_domain }}"
    line: "cname=pihole.{{ ansible_hostname }}.{{ homelab_domain }},{{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1

- name: Run container
  shell:
    cmd: "docker compose -f /data/services/pihole.yml up -d"

# register dns
- include_tasks: register_dns.yml

# Update the DNS records as well
- include_tasks: update.yml
