- name: Insert IP address and hostname into custom.list format
  lineinfile:
    path: "{{ playbook_dir }}/files/dns/custom.list"
    regexp: ".* {{ ansible_hostname }}.int.{{ homelab_domain }}"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.int.{{ homelab_domain }}"
    create: true
  delegate_to: 127.0.0.1
