
# register dns
- include_tasks: register_host.yml

# Update the DNS host records as well
- include_tasks: update_dns_hosts.yml

# Update the DNS host records as well
- include_tasks: update_dns_cnames.yml

- name: Restart PiHole
  command:
    cmd: "docker compose -f /data/services/pihole.yml restart"
  ignore_errors: true
